using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SecurityLibrary {
    public class Monoalphabetic : ICryptographicTechnique<string, string> {
        public string Analyse(string plainText, string cipherText) {
            String alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            String k = "**************************";
            char[] key = k.ToCharArray();
            foreach (char c in plainText) {

                int c_idx = plainText.IndexOf(c); //index of letter in plain 
                char c_ = cipherText[c_idx]; //letter

                int k_idx = alpha.IndexOf(char.ToUpper(c));//original index of in alphabetic

                key[k_idx] = c_;


            }
            int x = 0;
            foreach (char c in alpha) {
                if (key.Contains(c) == false) {
                    for (int i = x; i < k.Length; i++) {
                        if (key[i] == '*') {
                            key[i] = c;
                            x = i + 1;
                            break;
                        }


                    }

                }

            }
            k = new string(key);
            // Console.WriteLine(k);
            return k.ToLower();
        }

        public string Decrypt(string cipherText, string key) {
            String alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

            String p = "";
            foreach (char l in cipherText) {

                //Console.WriteLine(l);
                int c_idx = key.IndexOf(char.ToLower(l));
                //Console.WriteLine(c_idx);
                p += (char)alpha[c_idx];
            }
            return p.ToLower();
        }

        public string Encrypt(string plainText, string key) {
            String alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

            String c = "";
            foreach (char l in plainText.ToLower()) {
                int p_idx = alpha.IndexOf(char.ToUpper(l));

                c += (char)key[p_idx];
            }

            return c;
        }

        /// <summary>
        /// Frequency Information:
        /// E   12.51%
        /// T	9.25
        /// A	8.04
        /// O	7.60
        /// I	7.26
        /// N	7.09
        /// S	6.54
        /// R	6.12
        /// H	5.49
        /// L	4.14
        /// D	3.99
        /// C	3.06
        /// U	2.71
        /// M	2.53
        /// F	2.30
        /// P	2.00
        /// G	1.96
        /// W	1.92
        /// Y	1.73
        /// B	1.54
        /// V	0.99
        /// K	0.67
        /// X	0.19
        /// J	0.16
        /// Q	0.11
        /// Z	0.09
        /// </summary>
        /// <param name="cipher"></param>
        /// <returns>Plain text</returns>
        public string AnalyseUsingCharFrequency(string cipher) {
            string largePlain = "JULYPREVIOUSMONTHNEXTMONTHMEMBERSUPDATEFIRSTSCREENEDITORIALBACKONMYSOAPBOXWHYISITTHATUSEOFTHEENGLISHLANGUAGEISGETTINGSOVERYSLOPPYHOWLONGAGOWASITWHENGRAMMARCEASEDTOBEANESSENTIALELEMENTOFWRITINGADECENTESSAYAWHILEAGOTHEREWASACAMPAIGNTODOAWAYWITHTHEABERRANTAPOSTROPHENOWITSEEMSWENEEDANEWCAMPAIGNTOCONTENDWITHTHEABERRANTHYPHENYESIKNOWTHEREISAVASTDIFFERENCEBETWEENABLACKCABDRIVERANDABLACKCABDRIVERBUTNONEOFMYREFERENCEBOOKSINVITESHYPHENATIONOFBLACKCABORDRIVERANEXTREMEEXAMPLEPERHAPSBUTIMGETTINGTIREDOFSORTINGOUTHYPHENATEDWORDSANDREPLACINGTHEHYPHENWITHACOMMAORSEMICOLONORCREATINGANEWSENTENCENOOFCOURSEIMNOTPERFECTNOONEISBUTINOTONLYABHORTHEINAPPROPRIATEUSEOFAHYPHENIALSORECOGNISEASPLITINFINITIVEWHENISEEONEITMAYBEACCEPTABLEFORTHESTARSHIPENTERPRISETOBOLDLYGOBUTIDONOTTHINKTHATLOCALORGANISATIONSSHOULDBEENCOURAGEDTOPROACTIVELYENGAGEDEPARTMENTOFWORKANDPENSIONSPRESSRELEASEIRELYONJULIETOCHECKTHEPROOFCOPYOFUPDATEBEFOREYOUSEEITANDSHEWONTLETCARELESSUSEOFGRAMMARSLIPTHROUGHOOPSISHOULDNOWSAYIUSEDTORELYONJULIEASIWROTETHATBEFORESHEHANDEDINHERNOTICENOBEFOREYOUASKIDONTTHINKITWASANYTHINGISAIDORDIDSPECIFICALLYASMANYREADERSWILLKNOWADSETPROVIDEDOFFICESPACEFORTHEADMINISTRATIONFUNCTIONSOFNAEGAWITHJULIEWORKINGFORNAEGAFORTWELVEHOURSAWEEKINTHATSPACETHATCONTRACTCAMETOANABRUPTENDINMAYANDICANNOTFINDWORKWITHINTHEADSETSETUPTOMAKEUPTHOSEMISSINGHOURSSORATHERTHANTRYTOFINDASECONDPARTTIMEJOBJULIEHASFOUNDHERSELFFULLTIMEWORKSHEWILLBEGREATLYMISSEDNOTLEASTFORHERABILITYTOSPOTANABERRANTHYPHENORAPOSTROPHECHANGESAREAFOOTWELLTHEYWOULDHAVETOBEWOULDNTTHEYDAWNYESTHEONEWHOWRITESTHEFUNNYCOMMENTSINUPDATEWILLBETAKINGOVERJULIESJOBOFTHENEWSPAPERSTHETIMINGISRIGHTASHERYOUNGESTSTARTSFULLTIMESCHOOLINSEPTEMBERRUTHWARNERWHOMMANYOFYOUALREADYKNOWASADSETSDATAMANAGERALSOINCONTROLOFTHEWEBSITEWILLBETAKINGOVERASMEMBERSHIPSECRETARYASFORHELPINTHEOFFICEIMINTERVIEWINGFOURPEOPLETOMORROWANDEXPECTTOBEABLETOAPPOINTONEOFTHEMTOSTARTONAUGUSTTHATGIVESHERTHEYAREALLFEMALETHREEWEEKSTOFINDHERFEETBEFOREIGOONHOLIDAYFORAWEEKINEVERTHOUGHTTHATIDBEBLESSINGMOBILEPHONESBUTITHINKTHATITMIGHTBENEEDEDANDTHEFAMILYWILLFORONCEHAVETOACCEPTITTHEWIDERWORLDTHELSCHASBEENTAKINGABITOFAHAMMERINGTHISMONTHWITHTHEASSOCIATIONOFCOLLEGESSTILLASSERTINGTHATTHEREARECLEARTENSIONSBETWEENTHECENTREANDTHEARMSANDINSTITUTEOFDIRECTORSSAYINGTHATTHEORGANISATIONHASMADELITTLEIFANYIMPACTONBUSINESSTHEFUNDINGOFLEARNINGANDTHEPEOPLEWHOUNDERTAKEITCONTINUESTODOMINATETHEEDUCATIONALPRESSWHILSTTHEPROVISIONOFADDITIONALMONEYUNDERTHECOMPREHENSIVESPENDINGREVIEWISWELCOMEDITSNOTENOUGHISITEVERITSEEMSTHETHEPOWERSTHATBEAREWAKINGUPTOTHEIDEATHATMAYBEJUSTMAYBEAIMINGFORAPAPERLESSSOCIETYWASNOTSUCHAGOODIDEAATLEASTNOTUNTILYOUCANBECERTAINOFBEINGABLETORETRIEVETHEINFORMATIONCREATEDWELCOMETONEWMEMBERSCAMBRIDGESHIREGRIDFORLEARNINGCONTACTLILYDAINTERTELLOGWOODMANAGEMENTCONSULTANTSLTDCONTACTVELMABENNETTTELDETAILSOFTHEWORKOFTHESETWOORGANISATIONSWILLBEPLACEDONTHEADSETWEBSITEJUSTASSOONASWEGETTHEMTOTOPOFPAGETOINDEXCIPDURGESCAUTIONONEMPLOYEERIGHTSREVIEWPATRICIAHEWITTSECRETARYOFSTATEFORTRADEANDINDUSTRYHASTODAYJULYLAUNCHEDAREVIEWOFTHEEMPLOYMENTRELATIONSACTTHEREVIEWWILLLOOKATCOMPULSORYTRADEUNIONRECOGNITIONMEASURESALTHOUGHCHANGESWILLBELIMITEDACCORDINGTOTHEDTITHECIPDEXPRESSESCAUTIONABOUTTHEINITIATIVEDIANESINCLAIRLEADPUBLICPOLICYADVISERRESPONDEDTHELAWISWORKINGWELLATTHEMOMENTANDISFINELYBALANCEDBETWEENEMPLOYERSANDEMPLOYEESFORINSTANCEMANYTRADEUNIONSARECURRENTLYWINNINGCLAIMSUNDERTHEACTWEHOPETHATTHEGOVERNMENTALLOWSTHISLEGISLATIONTOBEDDOWNBEFORECHANGESARECONSIDEREDTHEDTIHASALSOLAUNCHEDACONSULTATIONDOCUMENTTODAYONIMPLEMENTINGTHEEUDIRECTIVEONINFORMINGANDCONSULTINGSTAFFINTHEUKTHISISDUETOCOMEINTOEFFECTINTHEUKFORORGANISATIONSOFMORETHANSTAFFBYMARCHANDFORSMALLERORGANISATIONSBYMARCHORGANISATIONSEMPLOYINGLESSTHANPEOPLEARELIKELYTOBEEXCLUDEDCIPDPRESSRELEASEJULYTOTOPOFPAGETOINDEXJOHNSONHERALDSNEWERAFORBRITISHFIRMSNEWPROPOSALSTOCUTREDTAPEANDSAVESMALLBUSINESSESAROUNDMILLIONAYEARWEREUNVEILEDTODAYJULYWITHTHEPUBLICATIONOFTHEGOVERNMENTWHITEPAPERMODERNISINGCOMPANYLAWTHEWHITEPAPERREFLECTSTHECHANGESINTHEBUSINESSENVIRONMENTINRECENTYEARSPARTICULARLYTHEGROWTHOFSMALLBUSINESSESANDADVANCESINCOMMUNICATIONSTECHNOLOGYANDINCLUDESPLANSTOSIMPLIFYTHELAWANDREDUCEBURDENSONSMALLFIRMSIMPROVETRANSPARENCYTOINCREASECONFIDENCEINBUSINESSANDIMPROVEGOVERNANCETOENCOURAGEANDSUPPORTRESPONSIBLEBUSINESSOTHERKEYPROPOSALSINCLUDEDIRECTORSDUTIESWILLBESETOUTCLEARLYINSTATUTEFORTHEFIRSTTIMECORPORATEDIRECTORSWILLBEPROHIBITEDPRIVATECOMPANIESNOLONGERWILLHAVETOAPPOINTCOMPANYSECRETARIESPRIVATECOMPANIESNOLONGERWILLHAVETOHOLDAGMSUNLESSMEMBERSWANTTHEMCOMPANIESWILLBEABLETOEXPLOITTHEINTERNETANDEMAILTOMAKEDECISIONSCOMPANIESWILLHAVESIMPLERREPORTSANDACCOUNTSACCOUNTSWILLBEFILEDMOREQUICKLYWITHINSEVENMONTHSFORPRIVATECOMPANIESANDSIXMONTHSFORPUBLICCOMPANIESQUOTEDCOMPANIESWILLHAVETOPOSTREPORTSONWEBSITESBEFORETHISTHELARGESTCOMPANIESWILLPUBLISHANOPERATINGANDFINANCIALREVIEWCOMPANIESANDTHEIRDIRECTORSCONVICTEDOFFLOUTINGCOMPANYLAWCOULDBENAMEDINACENTRALREGISTERTHEWHITEPAPERISAVAILABLEONLINEATWWWDTIGOVUKCOMPANIESBILLASUMMARYOFTHEMEASURESOFPARTICULARINTERESTTOSMALLBUSINESSISALSOAVAILABLEDTIPRESSRELEASEPJULYTOTOPOFPAGETOINDEXCBIPRAISESCOMPANYLAWREFORMPLANSTHECONFEDERATIONOFBRITISHINDUSTRYCBIISBACKINGGOVERNMENTPROPOSALSTOREFORMCOMPANYLAWITISHOPEDTHATTHISWILLSIMPLIFYTHEREGIMEFORSMALLFIRMSWHILEIMPROVINGACCOUNTABILITYFORLARGEROGANISATIONSTHECBIISPRAISINGGOVERNMENTPLANSTOIMPLEMENTTHERECOMMENDATIONSOFTHECOMPANYLAWREVIEWITISHOPEDTHATTHISWILLMAKETHELAWCLEARERANDMOREEFFECTIVEHRLOOKJULYTOTOPOFPAGETOINDEXPATRICIAHEWITTANNOUNCESNEWAPPOINTMENTSTOTHESMALLBUSINESSCOUNCILSECRETARYOFSTATEFORTRADEANDINDUSTRYPATRICIAHEWITTTODAYJULYANNOUNCEDTHEFULLNEWMEMBERSHIPOFTHESMALLBUSINESSCOUNCILSBCTHEMEMBERSWORKWITHTHECHAIRMANWILLIAMSARGENTTOADVISETHEGOVERNMENTONISSUESAFFECTINGSMALLBUSINESSESTHESBCREPRESENTSAWIDERANGEOFSECTORSINCLUDINGMANUFACTURINGRETAILSOCIALENTERPRISETOURISMBUSINESSSUPPORTENVIRONMENTALBUSINESSESMEDIAANDENTERTAINMENTRECRUITMENTACCOUNTANCYANDACADEMIATHEMEMBERSHIPREPRESENTSALLPARTSOFTHEUKANDINCLUDESPEOPLEOFDIFFERENTAGESANDBACKGROUNDSDTIPRESSRELEASEPJULYUPDATECOMMENTTHEPRESSRELEASELISTSTHEPEOPLEWITHSHORTBIOGSANDSOMEOFTHEMREALLYAREFROMSMALLBUSINESSESTOTOPOFPAGETOINDEXSMALLBUSINESSSECTORGROWTHEQUIVALENTTOOVERNEWSTARTUPSEVERYDAYNIGELGRIFFITHSHAILSNETINCREASEINBUSINESSPOPULATIONNEWFIGURESPUBLISHEDTODAYJULYSHOWTHEREWASANETINCREASEOFMORETHANFIRMSOPERATINGINTHEUKINCOMPAREDTOTHEPREVIOUSYEAREQUIVALENTTOOVERNEWBUSINESSESSTARTINGUPEVERYDAYACCORDINGTONEWSTATISTICSFROMTHEDTISSMALLBUSINESSSERVICESBSTHEBUSINESSPOPULATIONTOTALLEDLASTYEARCOMPAREDTOINTHEYEAROTHERFINDINGSSHOWTHEREWEREMILLIONMOREBUSINESSESTHANINTHEFIRSTYEARFORWHICHCOMPARABLEFIGURESAREAVAILABLETHENUMBEROFMEDIUMSIZEDBUSINESSESREACHEDFORTHEFIRSTTIMEINSEVENYEARSANDATLEASTOFBUSINESSESINALLINDUSTRIESWERESMESTHEFULLSTATISTICSCANBEDOWNLOADEDFROMTHESMALLBUSINESSSERVICEWEBSITEATWWWSBSGOVUKSTATISTICSDTIPRESSRELEASEPJULYTHEGAMECOMESTIMATESTHATWORLDCUPABSENTEEISMCOSTTHEUKAROUNDMILLIONTHISFIGUREISONLYATENTHOFTHEPREDICTEDCOSTSINCEMANYEMPLOYERSWERECOOPERATIVEANDALLOWEDEMPLOYEESTOEITHERCHANGETHEIRHOURSORWATCHTHEMATCHESATWORKHOWEVEROFFANSSTILLADMITTEDTOTAKINGATLEASTONEDAYASSICKLEAVEIRSEMPLOYMENTREVIEWISSUEJULYTOTOPOFPAGETOINDEXCOMMUNICATIONSKILLSLACKINGATTHETOPACCORDINGTONEWRESEARCHFROMTHEAZIZCORPORATIONBRITAINSTOPBUSINESSLEADERSARELARGELYUNHEARDUNRECOGNISEDANDCONSIDEREDUNABLETOCOMMUNICATEEFFECTIVELYBYTHEIRBUSINESSPEERSTHERESEARCHREVEALEDTHATWHILEOFUKCOMPANYDIRECTORSCONSIDERUSBUSINESSEXECUTIVESTOHAVEANEXCELLENTORGOODMEDIAIMAGEANDREPUTATIONONLYBELIEVETHESAMEOFUKEXECUTIVESINADDITIONFEELTHATTHEMEDIAIMAGEOFTHEUKSLEADINGBUSINESSEXECUTIVESISINNEEDOFIMPROVEMENTTRAININGZONELEARNINGWIREISSUEJULYTOTOPOFPAGETOINDEXTHEHUMBLELEADERANARTICLEINBULLETPOINTJUNEISSUEARGUESTHATHAVINGALARGERTHANLIFECORPORATEHEROASALEADERCANBEDETRIMENTALTOANORGANISATIONTHEMAINCRITICISMSOFTHISTYPEOFLEADERARETHATTHEYARESELFSERVINGMOREINTERESTEDINSELFPROMOTIONANDCELEBRITYTHANTEAMWORKTHEARTICLEFURTHERSUGGESTSTHATINMANYCASESTHEYFAILTOADDVALUEDONOTDELIVERSUSTAINABLERESULTSANDDONTWORKTOIMPROVEPERFORMANCETHEARTICLETELLSUSTHATTRULYTRANSFORMATIONALLEADERSHAVEANEQUALRATIOOFHUMILITYANDPROFESSIONALWILLTHEYAREABLEMANAGERSRATHERTHANAFGUREHEADFORTHEMEDIAANDCANENGENDEREMPLOYEETRUSTCOMMITMENTANDLOYALTYTHEYWILLALSOHAVEADESIRETOSHUNPUBLICITYCHANNELAMBTIONINTODEVELOPINGTHECOMPANYNOTTHEMSELVESGIVECREDITTOOTHERSAROUNDTHEMANDDESPISEMEDIOCRITYTOTOPOFPAGETOINDEXWHATAMESSPARTICPATIONASASMPLEMANAGERIALRULETOCOMPLEXIFYORGANISATIONSACTUALLYASERIOUSRESEARCHPAPERWHICHLOOKSATSOMEOFTHESIMPLERULESOFMANAGEMENTWHCHNTHEENDCANFOULUPOURLIVESFORGOODBUTONLYIFWELETTHEMWEALLIASSUMEKNOWOFTHEHORSEMADEBYACOMMITTEEINTODAYSCONSULTATIVECLMATEWECOULDBEHEADINGFORTRYINGTODEALINCAMELSUNLESSULTIMATELYTHEMANAGERIETHESINGLEPERSONRESPONSIBLEFORMAKINGANDIMPLEMENTNGTHEDECISIONDECIDESOURHORSESSHOULDNOTHAVEHUMPSWHETHERONEORTWOISIMMATERIALSOINTHEENDWEHAVETHEAUTOCRATICDICTATORIALVICTORIANPARENTWHOSEOFFSPRINGMIGHTIFDARINGTOQUESTIONRECEIVETHERESPONSEBECAUSEISAYITISJOURNALOFMANAGEMENTSTUDIESMARCHUPDATECOMMENTONTHEOTHERHANDTHEEUROPEANDIRECTIVESAYSTHOUSHALTCONSULTANDATLENGTHUNLESSTHEREARELESSTHANSTAFFINYOURORGANISATIONSORRYGUYSTHATMEANSTHATICANCONTINUETOBETHEAUTOCRATCDCTATORIALPARENTTYPEATLEASTINLAWIFNOTREALITYTOTOPOFPAGETOINDEXLEADERSNEEDMORETRAININGAYEARAFTERTHELIBRARYWORLDSRECRUTRETANANDLEADREPORTWARNEDOFFALLINGSTANDARDSINEXECUTIVEABILITYMUSEUMSAREFACINGASIMLARLEADERSHIPCRISISSPEAKINGATTHEANNUALMUSEUMDRECTORSCONFERENCELIZAMOSOFTHECOUNCILFOREXCELLENCEINMANAGEMENTANDLEADERSHIPTOLDDELEGATESTHATTHEYSHOULDHEEDTHEDSQUETBEINGVOICEDBYJUNIORANDMIDDLEMANAGERSINTHEPUBLICSECTORACCORDNGTOARECENTREPORTOFJUNIORANDMIDDLEMANAGERSCLAIMTHATLEADERSHPNTHEIRORGANISATIONISPOORMSAMOSBELIEVESTHATTHISMATTERSBECAUSEGOODLEADERSCANNSPIREANDENERGISETHEIREMPLOYEESWHICHHASAPOSTVEEFFECTONPERFORMANCELIBRARYANDINFORMATIONUPDATEJULYVOLTOTOPOFPAGETOINDEXPATHTOTHEGATEWAYISCLEAREDAYEARAGOANENTREPRENEURSEEKINGHELPTOSETUPACOMPANYINGLASGOWRISKEDBEINGKNOCKEDDOWNINARUSHOFAGENCIESBRANDISHINGMORETHANDIFFERENTSUPPORTPRODUCTSANDSERVICESNEWBUSINESSESFACEDABEWILDERINGCHOICEOFDIFFERENTPUBLICSECTORAGENCIESPROVIDINGACCESSTOOVERBUSINESSSUPPORTPARTNERSHPSMOSTLYKNOWNBYCONFUSINGTHREELETTERACRONYMSYETDESPITETHEWELTEROFSERVICESAVAILABLEWITHLITERALLYHUNDREDSOFADVISERSGRANTSANDTRAININGSCHEMESONOFFERRESEARCHSHOWEDTHATGLASGOWURGENTLYNEEDEDTOFINDBETTERWAYSTOIMPROVEITSBUSINESSBIRTHRATEANDITSINDIGENOUSCOMPANYSURVIVALRATETHEVULNERABILITYOFSMALLANDMEDIUMSIZEDENTERPRISESSMESTOFAILURENTHEIREARLYYEARSISCLEARANDINGLASGOWONLYOFSMESSURVIVELONGERTHANTHREEYEARSCOMPAREDTOTHENATIONALTHREEYEARSURVIVALRATEOFONTOPOFLOWERTHANAVERAGESURVIVALRATESGLASGOWALSOHADAPROBLEMWITHEUROPEANBUSINESSGRANTSBEINGLEFTUNCLAIMEDBECAUSEELIGIBLECOMPANESDDNOTAPPLYFORTHECASHONOFFERDUNCANTANNAHILLCHIEFEXECUTIVEOFGLASGOWCHAMBEROFCOMMERCESEZEDTHECHANCETOPOOLTHERESOURCESOFTHEPRIVATEANDPUBLCSECTORSINAMAJOREFFORTTOADDRESSTHESHORTCOMINGSOFTHESYSTEMANDCREATEASNGLEPOINTOFENTRYFORCOMPANIESSEEKNGHELPATANYSTAGEOFTHEIRDEVELOPMENTSMALLBUSINESSGATEWAYISATVALERIEDARROCHSCOTTISHHERALDJULYMYSCHOOLDAYSWERETHEHAPPESTDAYSOFMY".ToLower();
            string largeCipher = cipher;
            //use largeplain to create english frequency table
            Dictionary<char, int> dict = largePlain
                                         .GroupBy(c => c)
                                         .ToDictionary(gr => gr.Key, gr => gr.Count());

            var e_table = dict.OrderByDescending
                (x => x.Value).ToDictionary(x => x.Key, x => x.Value);


            //Console.WriteLine("*******c_ table*************");

            Dictionary<char, int> dictt = largeCipher
                             .GroupBy(c => c)
                             .ToDictionary(gr => gr.Key, gr => gr.Count());

            var c_table = dictt.OrderByDescending
                (x => x.Value).ToDictionary(x => x.Key, x => x.Value);

            //foreach (var item in c_table.Keys)


            Dictionary<char, char> final_tabale = new Dictionary<char, char>();


            for (int i = 0; i < 26; i++) {
                final_tabale.Add(c_table.ElementAt(i).Key, e_table.ElementAt(i).Key);


            }
            //Console.WriteLine("*******final table****");

            char[] final_plain = largeCipher.ToCharArray();
            for (int i = 0; i < largeCipher.Length; i++) {
                char l = char.ToUpper(largeCipher[i]);
                final_plain[i] = final_tabale[l];

            }
            // Console.WriteLine("*******final plain text****");
            string s = new string(final_plain);
            return s;
        }
    }
}